
import { Category, Condition, Product, User } from './types';

export const APP_NAME = 'ENLIZZO';

export const HOSTELS = [
  'Aravali', 'Girnar', 'Himadri', 'Jwalamukhi', 'Kailash', 
  'Karakoram', 'Kumaon', 'Nilgiri', 'Satpura', 'Shivalik', 
  'Udaigiri', 'Vindhyachal', 'Zanskar', 'Dronagiri', 
  'Saptagiri', 'Sahyadri', 'Nalanda'
];

export const SEARCH_SUFFIXES = [
  "Cycle",
  "Books",
  "Calculator",
  "Mattress",
  "Kettle",
  "Table",
  "Cooler",
  "Lab Coat",
  "Drafter",
  "Speaker"
];

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Aravind Kumar',
  email: 'aravind.k@iitd.ac.in',
  hostel: 'Karakoram',
  avatarUrl: 'https://picsum.photos/id/64/200/200',
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    title: 'RD Sharma Mathematics Vol 1 & 2',
    price: 450,
    originalPrice: 900,
    description: 'Barely used, good condition for JEE prep or 1st year recap.',
    category: Category.Books,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/24/400/400'],
    sellerId: 'u2',
    sellerName: 'Rohan Das',
    sellerHostel: 'Nilgiri',
    createdAt: '2024-10-10',
    likes: 12,
    isSold: false,
  },
  {
    id: 'p2',
    title: 'Logitech Wireless Mouse',
    price: 0,
    originalPrice: 800,
    description: 'Left button slightly sticky, but works. Giving away for free.',
    category: Category.Electronics,
    condition: Condition.Fair,
    images: ['https://picsum.photos/id/30/400/400'],
    sellerId: 'u3',
    sellerName: 'Sneha G',
    sellerHostel: 'Himadri',
    createdAt: '2024-10-12',
    likes: 45,
    isSold: false,
  },
  {
    id: 'p3',
    title: 'Atlas Cycle - Black',
    price: 1500,
    originalPrice: 4500,
    description: 'Needs a tyre change, otherwise solid frame. Moving out sale.',
    category: Category.Cycles,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/70/400/400'],
    sellerId: 'u4',
    sellerName: 'Vikram Singh',
    sellerHostel: 'Aravali',
    createdAt: '2024-10-14',
    likes: 8,
    isSold: false,
  },
  {
    id: 'p4',
    title: 'Scientific Calculator fx-991ES',
    price: 300,
    originalPrice: 1200,
    description: 'Essential for engineering exams. Fully functional.',
    category: Category.Stationery,
    condition: Condition.LikeNew,
    images: ['https://picsum.photos/id/60/400/400'],
    sellerId: 'u1',
    sellerName: 'Aravind Kumar',
    sellerHostel: 'Karakoram',
    createdAt: '2024-10-15',
    likes: 2,
    isSold: false,
  },
  {
    id: 'p5',
    title: 'Study Table Lamp',
    price: 200,
    originalPrice: 550,
    description: 'Rechargeable LED lamp. Battery lasts 4 hours.',
    category: Category.Furniture,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/36/400/400'],
    sellerId: 'u5',
    sellerName: 'Priya M',
    sellerHostel: 'Kailash',
    createdAt: '2024-10-16',
    likes: 15,
    isSold: false,
  },
  {
    id: 'p6',
    title: 'Sony WH-CH510 Wireless Headphones',
    price: 1500,
    originalPrice: 3000,
    description: 'Great battery life (35 hours). Ear cups are slightly worn but sound is perfect.',
    category: Category.Electronics,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/1/400/400'],
    sellerId: 'u6',
    sellerName: 'Aditya Verma',
    sellerHostel: 'Satpura',
    createdAt: '2024-10-17',
    likes: 20,
    isSold: false,
  },
  {
    id: 'p7',
    title: 'Electric Kettle 1.5L (Prestige)',
    price: 600,
    originalPrice: 1200,
    description: 'Boils water in 2 mins. Essential for Maggi nights.',
    category: Category.Electronics,
    condition: Condition.LikeNew,
    images: ['https://picsum.photos/id/250/400/400'],
    sellerId: 'u7',
    sellerName: 'Kavya S',
    sellerHostel: 'Kailash',
    createdAt: '2024-10-17',
    likes: 5,
    isSold: false,
  },
  {
    id: 'p8',
    title: 'Single Bed Mattress (Cotton)',
    price: 800,
    originalPrice: 2500,
    description: 'Standard hostel bed size. Clean and no stains. Moving out.',
    category: Category.Furniture,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/300/400/400'],
    sellerId: 'u8',
    sellerName: 'Rahul Mehta',
    sellerHostel: 'Vindhyachal',
    createdAt: '2024-10-18',
    likes: 3,
    isSold: false,
  },
  {
    id: 'p9',
    title: 'Introduction to Algorithms (CLRS) 3rd Ed',
    price: 900,
    originalPrice: 2200,
    description: 'The bible of CS. Hardcover. No highlights inside.',
    category: Category.Books,
    condition: Condition.LikeNew,
    images: ['https://picsum.photos/id/24/400/400'],
    sellerId: 'u2',
    sellerName: 'Rohan Das',
    sellerHostel: 'Nilgiri',
    createdAt: '2024-10-18',
    likes: 45,
    isSold: false,
  },
  {
    id: 'p10',
    title: 'Yonex Muscle Power Badminton Racket',
    price: 1200,
    originalPrice: 2800,
    description: 'Gutting recently changed (BG 65). Grip needs replacement.',
    category: Category.Other,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/400/400/400'],
    sellerId: 'u9',
    sellerName: 'Suresh Raina',
    sellerHostel: 'Kumaon',
    createdAt: '2024-10-19',
    likes: 12,
    isSold: false,
  },
  {
    id: 'p11',
    title: 'White Lab Coat (Size M)',
    price: 200,
    originalPrice: 450,
    description: 'Used for one semester of Chemistry lab. Washed and ironed.',
    category: Category.Clothing,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/500/400/400'],
    sellerId: 'u3',
    sellerName: 'Sneha G',
    sellerHostel: 'Himadri',
    createdAt: '2024-10-19',
    likes: 1,
    isSold: false,
  },
  {
    id: 'p12',
    title: 'Mini Drafter for Engg Drawing',
    price: 250,
    originalPrice: 650,
    description: 'Omega brand. Mechanics are smooth. Scale edges are sharp.',
    category: Category.Stationery,
    condition: Condition.LikeNew,
    images: ['https://picsum.photos/id/600/400/400'],
    sellerId: 'u10',
    sellerName: 'Prateek Jain',
    sellerHostel: 'Zanskar',
    createdAt: '2024-10-20',
    likes: 6,
    isSold: false,
  },
  {
    id: 'p13',
    title: 'Btwin MyBike (White)',
    price: 3500,
    originalPrice: 6000,
    description: '1 year old. Single speed. Smooth ride. Lock included.',
    category: Category.Cycles,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/146/400/400'],
    sellerId: 'u4',
    sellerName: 'Vikram Singh',
    sellerHostel: 'Aravali',
    createdAt: '2024-10-20',
    likes: 28,
    isSold: false,
  },
  {
    id: 'p14',
    title: 'Plastic Chair (Nilkamal)',
    price: 300,
    originalPrice: 650,
    description: 'Sturdy backrest. Good for extra seating in room.',
    category: Category.Furniture,
    condition: Condition.Fair,
    images: ['https://picsum.photos/id/800/400/400'],
    sellerId: 'u11',
    sellerName: 'Dev Patel',
    sellerHostel: 'Girnar',
    createdAt: '2024-10-21',
    likes: 4,
    isSold: false,
  },
  {
    id: 'p15',
    title: 'JBL Go 2 Portable Speaker',
    price: 1100,
    originalPrice: 1800,
    description: 'Waterproof. Blue color. Sound is crisp.',
    category: Category.Electronics,
    condition: Condition.LikeNew,
    images: ['https://picsum.photos/id/900/400/400'],
    sellerId: 'u5',
    sellerName: 'Priya M',
    sellerHostel: 'Kailash',
    createdAt: '2024-10-21',
    likes: 18,
    isSold: false,
  },
  {
    id: 'p16',
    title: 'Table Tennis Racket (GKI)',
    price: 0,
    originalPrice: 600,
    description: 'Rubber is worn out on one side. Good for beginners to practice against wall. Donation.',
    category: Category.Other,
    condition: Condition.Poor,
    images: ['https://picsum.photos/id/1000/400/400'],
    sellerId: 'u12',
    sellerName: 'Amit Roy',
    sellerHostel: 'Udaigiri',
    createdAt: '2024-10-22',
    likes: 8,
    isSold: false,
  },
  {
    id: 'p17',
    title: 'HC Verma Concepts of Physics (Vol 1 & 2)',
    price: 500,
    originalPrice: 900,
    description: 'Classic. Minimal pencil marks.',
    category: Category.Books,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/24/400/400'],
    sellerId: 'u13',
    sellerName: 'Neha Gupta',
    sellerHostel: 'Himadri',
    createdAt: '2024-10-22',
    likes: 22,
    isSold: false,
  },
  {
    id: 'p18',
    title: 'Extension Board (4 Sockets)',
    price: 250,
    originalPrice: 500,
    description: 'Wire length 2 meters. Surge protection included.',
    category: Category.Electronics,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/200/400/400'],
    sellerId: 'u6',
    sellerName: 'Aditya Verma',
    sellerHostel: 'Satpura',
    createdAt: '2024-10-23',
    likes: 9,
    isSold: false,
  },
  {
    id: 'p19',
    title: 'Wooden Laptop Table',
    price: 400,
    originalPrice: 900,
    description: 'Foldable legs. Adjustable height. Cup holder.',
    category: Category.Furniture,
    condition: Condition.LikeNew,
    images: ['https://picsum.photos/id/300/400/400'],
    sellerId: 'u1',
    sellerName: 'Aravind Kumar',
    sellerHostel: 'Karakoram',
    createdAt: '2024-10-23',
    likes: 14,
    isSold: false,
  },
  {
    id: 'p20',
    title: 'Bajaj Induction Cooktop',
    price: 1800,
    originalPrice: 3200,
    description: '1 year old. Works perfectly. Saving on hostel mess bills.',
    category: Category.Electronics,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/292/400/400'],
    sellerId: 'u14',
    sellerName: 'Simran Kaur',
    sellerHostel: 'Sahyadri',
    createdAt: '2024-10-24',
    likes: 33,
    isSold: false,
  },
  {
    id: 'p21',
    title: 'Engineering Mechanics - Statics',
    price: 350,
    originalPrice: 750,
    description: 'Standard text for first year.',
    category: Category.Books,
    condition: Condition.New,
    images: ['https://picsum.photos/id/24/400/400'],
    sellerId: 'u8',
    sellerName: 'Rahul Mehta',
    sellerHostel: 'Vindhyachal',
    createdAt: '2024-10-24',
    likes: 5,
    isSold: false,
  },
  {
    id: 'p22',
    title: 'IIT Delhi Hoodie (Blue, Size L)',
    price: 400,
    originalPrice: 850,
    description: 'Board of Student Publications hoodie. Warm and cozy.',
    category: Category.Clothing,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/445/400/400'],
    sellerId: 'u10',
    sellerName: 'Prateek Jain',
    sellerHostel: 'Zanskar',
    createdAt: '2024-10-25',
    likes: 50,
    isSold: false,
  },
  {
    id: 'p23',
    title: 'Hercules Roadeo A50 Cycle',
    price: 5000,
    originalPrice: 12000,
    description: '21 gears (Shimano). Disc brakes. Dual suspension. Beast.',
    category: Category.Cycles,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/70/400/400'],
    sellerId: 'u15',
    sellerName: 'Varun Sharma',
    sellerHostel: 'Shivalik',
    createdAt: '2024-10-25',
    likes: 41,
    isSold: false,
  },
  {
    id: 'p24',
    title: 'Casio fx-82MS Calculator',
    price: 300,
    originalPrice: 550,
    description: 'Basic scientific calculator. Allowed in exams.',
    category: Category.Stationery,
    condition: Condition.Fair,
    images: ['https://picsum.photos/id/60/400/400'],
    sellerId: 'u11',
    sellerName: 'Dev Patel',
    sellerHostel: 'Girnar',
    createdAt: '2024-10-26',
    likes: 2,
    isSold: false,
  },
  {
    id: 'p25',
    title: 'Acoustic Guitar with Bag',
    price: 2500,
    originalPrice: 5500,
    description: 'Yamaha F310 copy. Strings need changing. Good for learning.',
    category: Category.Other,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/450/400/400'],
    sellerId: 'u9',
    sellerName: 'Suresh Raina',
    sellerHostel: 'Kumaon',
    createdAt: '2024-10-26',
    likes: 19,
    isSold: false,
  }
];
