
import { Category, Condition, Product, User, CampusConfig } from './types';

export const APP_NAME = 'Enlizzo';

// --- CAMPUS CONFIGURATION ---
// STRICT DOMAIN ENFORCEMENT: Only specific .ac.in domains are allowed.
// No subdomains or aliases.
export const CAMPUSES: CampusConfig[] = [
  {
    id: 'iitd',
    slug: 'iitd',
    name: 'IIT Delhi',
    emailDomains: ['@iitd.ac.in'],
    hostels: [
      'Aravali', 'Girnar', 'Himadri', 'Jwalamukhi', 'Kailash', 
      'Karakoram', 'Kumaon', 'Nilgiri', 'Satpura', 'Shivalik', 
      'Udaigiri', 'Vindhyachal', 'Zanskar', 'Dronagiri', 
      'Saptagiri', 'Sahyadri', 'Nalanda'
    ],
    theme: { primary: '#4f46e5' }
  },
  {
    id: 'iitk',
    slug: 'iitk',
    name: 'IIT Kanpur',
    emailDomains: ['@iitk.ac.in'],
    hostels: ['Hall 1', 'Hall 2', 'Hall 3', 'Hall 4', 'Hall 5', 'Hall 6', 'Hall 7', 'Hall 8', 'Hall 9', 'Hall 10', 'Hall 11', 'Hall 12', 'Hall 13', 'Girls Hostel 1'],
    theme: { primary: '#ef4444' }
  },
  {
    id: 'iitr',
    slug: 'iitr',
    name: 'IIT Roorkee',
    emailDomains: ['@iitr.ac.in'],
    hostels: ['Azad', 'Cautley', 'Ganga', 'Govind', 'Jawahar', 'Radhakrishnan', 'Rajendra', 'Rajiv', 'Ravindra', 'Sarojini', 'Kasturba'],
    theme: { primary: '#059669' }
  },
  {
    id: 'iitb',
    slug: 'iitb',
    name: 'IIT Bombay',
    emailDomains: ['@iitb.ac.in'],
    hostels: ['Hostel 1', 'Hostel 2', 'Hostel 3', 'Hostel 4', 'Hostel 5', 'Hostel 6', 'Hostel 9', 'Hostel 10', 'Hostel 11', 'Hostel 12', 'Hostel 13', 'Hostel 14', 'Hostel 15', 'Hostel 16', 'Tansa'],
    theme: { primary: '#d97706' }
  },
  {
    id: 'iitm',
    slug: 'iitm',
    name: 'IIT Madras',
    emailDomains: ['@iitm.ac.in'],
    hostels: ['Brahmaputra', 'Cauvery', 'Ganga', 'Godavari', 'Jamuna', 'Krishna', 'Mahanadi', 'Mandakini', 'Narmada', 'Pampa', 'Saraswathi', 'Sharavati', 'Sindhu', 'Tamiraparani', 'Tapti'],
    theme: { primary: '#db2777' }
  }
];

// Helper to check domains
export const ALLOWED_DOMAINS = CAMPUSES.flatMap(c => c.emailDomains);

// Default hostels for types that might need it fallback (though mostly we use user.campus.hostels)
export const DEFAULT_HOSTELS = CAMPUSES[0].hostels;

export const SEARCH_SUFFIXES = [
  "Cycle",
  "Books",
  "Calculator",
  "Mattress",
  "Kettle",
  "Table",
  "Cooler",
  "Lab Coat",
  "Drafter",
  "Speaker"
];

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Yashvi Singh',
  email: 'yashvisingh@iitd.ac.in',
  hostel: 'Kailash',
  avatarUrl: 'https://picsum.photos/id/64/200/200',
  campusId: 'iitd', // Explicitly set for mock
  campusSlug: 'iitd'
};

// Update mock products to belong to IITD by default
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    slug: 'rd-sharma-mathematics-vol-1-2-a1b2',
    title: 'RD Sharma Mathematics Vol 1 & 2',
    price: 450,
    originalPrice: 900,
    description: 'Barely used, good condition for JEE prep or 1st year recap.',
    category: Category.Books,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/24/400/400'],
    sellerId: 'u2',
    sellerName: 'Rohan Das',
    sellerHostel: 'Nilgiri',
    createdAt: '2024-10-10',
    likes: 12,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p2',
    slug: 'logitech-wireless-mouse-c3d4',
    title: 'Logitech Wireless Mouse',
    price: 0,
    originalPrice: 800,
    description: 'Left button slightly sticky, but works. Giving away for free.',
    category: Category.Electronics,
    condition: Condition.Fair,
    images: ['https://picsum.photos/id/30/400/400'],
    sellerId: 'u3',
    sellerName: 'Sneha G',
    sellerHostel: 'Himadri',
    createdAt: '2024-10-12',
    likes: 45,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p3',
    slug: 'atlas-cycle-black-e5f6',
    title: 'Atlas Cycle - Black',
    price: 1500,
    originalPrice: 4500,
    description: 'Needs a tyre change, otherwise solid frame. Moving out sale.',
    category: Category.Cycles,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/70/400/400'],
    sellerId: 'u4',
    sellerName: 'Vikram Singh',
    sellerHostel: 'Aravali',
    createdAt: '2024-10-14',
    likes: 8,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p4',
    slug: 'scientific-calculator-fx-991es-g7h8',
    title: 'Scientific Calculator fx-991ES',
    price: 300,
    originalPrice: 1200,
    description: 'Essential for engineering exams. Fully functional.',
    category: Category.Stationery,
    condition: Condition.LikeNew,
    images: ['https://picsum.photos/id/60/400/400'],
    sellerId: 'u1',
    sellerName: 'Aravind Kumar',
    sellerHostel: 'Karakoram',
    createdAt: '2024-10-15',
    likes: 2,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p5',
    slug: 'study-table-lamp-i9j0',
    title: 'Study Table Lamp',
    price: 200,
    originalPrice: 550,
    description: 'Rechargeable LED lamp. Battery lasts 4 hours.',
    category: Category.Furniture,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/36/400/400'],
    sellerId: 'u5',
    sellerName: 'Priya M',
    sellerHostel: 'Kailash',
    createdAt: '2024-10-16',
    likes: 15,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p6',
    slug: 'sony-wh-ch510-wireless-headphones-k1l2',
    title: 'Sony WH-CH510 Wireless Headphones',
    price: 1500,
    originalPrice: 3000,
    description: 'Great battery life (35 hours). Ear cups are slightly worn but sound is perfect.',
    category: Category.Electronics,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/1/400/400'],
    sellerId: 'u6',
    sellerName: 'Aditya Verma',
    sellerHostel: 'Satpura',
    createdAt: '2024-10-17',
    likes: 20,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p7',
    slug: 'electric-kettle-1-5l-prestige-m3n4',
    title: 'Electric Kettle 1.5L (Prestige)',
    price: 600,
    originalPrice: 1200,
    description: 'Boils water in 2 mins. Essential for Maggi nights.',
    category: Category.Electronics,
    condition: Condition.LikeNew,
    images: ['https://picsum.photos/id/250/400/400'],
    sellerId: 'u7',
    sellerName: 'Kavya S',
    sellerHostel: 'Kailash',
    createdAt: '2024-10-17',
    likes: 5,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p8',
    slug: 'single-bed-mattress-cotton-o5p6',
    title: 'Single Bed Mattress (Cotton)',
    price: 800,
    originalPrice: 2500,
    description: 'Standard hostel bed size. Clean and no stains. Moving out.',
    category: Category.Furniture,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/300/400/400'],
    sellerId: 'u8',
    sellerName: 'Rahul Mehta',
    sellerHostel: 'Vindhyachal',
    createdAt: '2024-10-18',
    likes: 3,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p9',
    slug: 'introduction-to-algorithms-clrs-3rd-ed-q7r8',
    title: 'Introduction to Algorithms (CLRS) 3rd Ed',
    price: 900,
    originalPrice: 2200,
    description: 'The bible of CS. Hardcover. No highlights inside.',
    category: Category.Books,
    condition: Condition.LikeNew,
    images: ['https://picsum.photos/id/24/400/400'],
    sellerId: 'u2',
    sellerName: 'Rohan Das',
    sellerHostel: 'Nilgiri',
    createdAt: '2024-10-18',
    likes: 45,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p10',
    slug: 'yonex-muscle-power-badminton-racket-s9t0',
    title: 'Yonex Muscle Power Badminton Racket',
    price: 1200,
    originalPrice: 2800,
    description: 'Gutting recently changed (BG 65). Grip needs replacement.',
    category: Category.Other,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/400/400/400'],
    sellerId: 'u9',
    sellerName: 'Suresh Raina',
    sellerHostel: 'Kumaon',
    createdAt: '2024-10-19',
    likes: 12,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p11',
    slug: 'white-lab-coat-size-m-u1v2',
    title: 'White Lab Coat (Size M)',
    price: 200,
    originalPrice: 450,
    description: 'Used for one semester of Chemistry lab. Washed and ironed.',
    category: Category.Clothing,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/500/400/400'],
    sellerId: 'u3',
    sellerName: 'Sneha G',
    sellerHostel: 'Himadri',
    createdAt: '2024-10-19',
    likes: 1,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p12',
    slug: 'mini-drafter-for-engg-drawing-w3x4',
    title: 'Mini Drafter for Engg Drawing',
    price: 250,
    originalPrice: 650,
    description: 'Omega brand. Mechanics are smooth. Scale edges are sharp.',
    category: Category.Stationery,
    condition: Condition.LikeNew,
    images: ['https://picsum.photos/id/600/400/400'],
    sellerId: 'u10',
    sellerName: 'Prateek Jain',
    sellerHostel: 'Zanskar',
    createdAt: '2024-10-20',
    likes: 6,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p13',
    slug: 'btwin-mybike-white-y5z6',
    title: 'Btwin MyBike (White)',
    price: 3500,
    originalPrice: 6000,
    description: '1 year old. Single speed. Smooth ride. Lock included.',
    category: Category.Cycles,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/146/400/400'],
    sellerId: 'u4',
    sellerName: 'Vikram Singh',
    sellerHostel: 'Aravali',
    createdAt: '2024-10-20',
    likes: 28,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p14',
    slug: 'plastic-chair-nilkamal-a7b8',
    title: 'Plastic Chair (Nilkamal)',
    price: 300,
    originalPrice: 650,
    description: 'Sturdy backrest. Good for extra seating in room.',
    category: Category.Furniture,
    condition: Condition.Fair,
    images: ['https://picsum.photos/id/800/400/400'],
    sellerId: 'u11',
    sellerName: 'Dev Patel',
    sellerHostel: 'Girnar',
    createdAt: '2024-10-21',
    likes: 4,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p15',
    slug: 'jbl-go-2-portable-speaker-c9d0',
    title: 'JBL Go 2 Portable Speaker',
    price: 1100,
    originalPrice: 1800,
    description: 'Waterproof. Blue color. Sound is crisp.',
    category: Category.Electronics,
    condition: Condition.LikeNew,
    images: ['https://picsum.photos/id/900/400/400'],
    sellerId: 'u5',
    sellerName: 'Priya M',
    sellerHostel: 'Kailash',
    createdAt: '2024-10-21',
    likes: 18,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p16',
    slug: 'table-tennis-racket-gki-e1f2',
    title: 'Table Tennis Racket (GKI)',
    price: 0,
    originalPrice: 600,
    description: 'Rubber is worn out on one side. Good for beginners to practice against wall. Donation.',
    category: Category.Other,
    condition: Condition.Poor,
    images: ['https://picsum.photos/id/1000/400/400'],
    sellerId: 'u12',
    sellerName: 'Amit Roy',
    sellerHostel: 'Udaigiri',
    createdAt: '2024-10-22',
    likes: 8,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p17',
    slug: 'hc-verma-concepts-of-physics-vol-1-2-g3h4',
    title: 'HC Verma Concepts of Physics (Vol 1 & 2)',
    price: 500,
    originalPrice: 900,
    description: 'Classic. Minimal pencil marks.',
    category: Category.Books,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/24/400/400'],
    sellerId: 'u13',
    sellerName: 'Neha Gupta',
    sellerHostel: 'Himadri',
    createdAt: '2024-10-22',
    likes: 22,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p18',
    slug: 'extension-board-4-sockets-i5j6',
    title: 'Extension Board (4 Sockets)',
    price: 250,
    originalPrice: 500,
    description: 'Wire length 2 meters. Surge protection included.',
    category: Category.Electronics,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/200/400/400'],
    sellerId: 'u6',
    sellerName: 'Aditya Verma',
    sellerHostel: 'Satpura',
    createdAt: '2024-10-23',
    likes: 9,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p19',
    slug: 'wooden-laptop-table-k7l8',
    title: 'Wooden Laptop Table',
    price: 400,
    originalPrice: 900,
    description: 'Foldable legs. Adjustable height. Cup holder.',
    category: Category.Furniture,
    condition: Condition.LikeNew,
    images: ['https://picsum.photos/id/300/400/400'],
    sellerId: 'u1',
    sellerName: 'Aravind Kumar',
    sellerHostel: 'Karakoram',
    createdAt: '2024-10-23',
    likes: 14,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p20',
    slug: 'bajaj-induction-cooktop-m9n0',
    title: 'Bajaj Induction Cooktop',
    price: 1800,
    originalPrice: 3200,
    description: '1 year old. Works perfectly. Saving on hostel mess bills.',
    category: Category.Electronics,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/292/400/400'],
    sellerId: 'u14',
    sellerName: 'Simran Kaur',
    sellerHostel: 'Sahyadri',
    createdAt: '2024-10-24',
    likes: 33,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p21',
    slug: 'engineering-mechanics-statics-o1p2',
    title: 'Engineering Mechanics - Statics',
    price: 350,
    originalPrice: 750,
    description: 'Standard text for first year.',
    category: Category.Books,
    condition: Condition.New,
    images: ['https://picsum.photos/id/24/400/400'],
    sellerId: 'u8',
    sellerName: 'Rahul Mehta',
    sellerHostel: 'Vindhyachal',
    createdAt: '2024-10-24',
    likes: 5,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p22',
    slug: 'iit-delhi-hoodie-blue-size-l-q3r4',
    title: 'IIT Delhi Hoodie (Blue, Size L)',
    price: 400,
    originalPrice: 850,
    description: 'Board of Student Publications hoodie. Warm and cozy.',
    category: Category.Clothing,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/445/400/400'],
    sellerId: 'u10',
    sellerName: 'Prateek Jain',
    sellerHostel: 'Zanskar',
    createdAt: '2024-10-25',
    likes: 50,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p23',
    slug: 'hercules-roadeo-a50-cycle-s5t6',
    title: 'Hercules Roadeo A50 Cycle',
    price: 5000,
    originalPrice: 12000,
    description: '21 gears (Shimano). Disc brakes. Dual suspension. Beast.',
    category: Category.Cycles,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/70/400/400'],
    sellerId: 'u15',
    sellerName: 'Varun Sharma',
    sellerHostel: 'Shivalik',
    createdAt: '2024-10-25',
    likes: 41,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p24',
    slug: 'casio-fx-82ms-calculator-u7v8',
    title: 'Casio fx-82MS Calculator',
    price: 300,
    originalPrice: 550,
    description: 'Basic scientific calculator. Allowed in exams.',
    category: Category.Stationery,
    condition: Condition.Fair,
    images: ['https://picsum.photos/id/60/400/400'],
    sellerId: 'u11',
    sellerName: 'Dev Patel',
    sellerHostel: 'Girnar',
    createdAt: '2024-10-26',
    likes: 2,
    isSold: false,
    campusId: 'iitd'
  },
  {
    id: 'p25',
    slug: 'acoustic-guitar-with-bag-w9x0',
    title: 'Acoustic Guitar with Bag',
    price: 2500,
    originalPrice: 5500,
    description: 'Yamaha F310 copy. Strings need changing. Good for learning.',
    category: Category.Other,
    condition: Condition.Good,
    images: ['https://picsum.photos/id/450/400/400'],
    sellerId: 'u9',
    sellerName: 'Suresh Raina',
    sellerHostel: 'Kumaon',
    createdAt: '2024-10-26',
    likes: 19,
    isSold: false,
    campusId: 'iitd'
  }
];
